services:
  dev-container:
    build:
      # All paths are relative to .devcontainer
      context: ./common/nodejs
      dockerfile: ./Dockerfile
      target: devcontainer
      args:
        - NODE_VERSION=${NODE_VERSION?NODE_VERSION env var must be provided}
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: KEY_FOR_LOCALSTACK
      AWS_SECRET_ACCESS_KEY: SECRET_KEY_FOR_LOCALSTACK