volumes:
  vscode-server:
  vscode-server-insiders:

services:
  dev-container:
    build:
      args:
        - INSTALL_DOCKER=true
    volumes:
      # Permit docker access
      - /var/run/docker.sock:/var/run/docker.sock
